### ISSUE TITLE
Mijia LED Bulb cannot change brightness or color (instantly reverts back to original value)

### ISSUE THREAD

**Issue by sulliwane** [AlexxIT/XiaomiGateway3#1185]
Hello All,

I purchased this Mijia compatible LED Bulb:
![IMG_20231025_203635](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/d6886239-235e-4ae8-b267-b9ae6cf98ce0)
![IMG_20231025_203642](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/29112a18-bab9-49a4-9f78-70a433f95bad)

Control it through Xiaomi_gateway_3 (and Xiaomi Multimode 2):
![IMG_20231025_204818](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/34a4004c-8bdc-4f88-9fdc-092ddc7e98b3)

But as you can see on this video, when trying to change the brightness it always auto reverts back to brightness level set in the Mijia App:

https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/380cd659-b8f2-420f-b77b-e7ab7061d9dc

I found this error in the logs, not sure it's related to my above problem but still posting:
![Screenshot from 2023-10-25 21-34-55](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/8ea75ead-33fd-44e2-9012-39e7edbe9db5)

![Screenshot from 2023-10-25 21-33-54](https://github.com/AlexxIT/XiaomiGateway3/assets/1733686/b49aea70-5db6-4c94-8fd6-6d82af9d6e67)

Any help would me much appreciated!! Thanks in advance :)

**Comment by dixon777** [comment]
When this entity "night_light_time" is created, [the attribute self._attr_native_value is initialized to empty string ](https://github.com/AlexxIT/XiaomiGateway3/blob/9ed02337dc119f21ea37090778f51d020f6b08e8/custom_components/xiaomi_gateway3/text.py#L25). Before self._attr_native_value is updated with the value obtained from the device, the function self.state is called and [self._attr_native_value does not match the attribute self._attr_pattern](https://github.com/home-assistant/core/blob/9cc7012d3217e9b3effbc7a9379526727cb64860/homeassistant/components/text/__init__.py#L153). Therefore, the error shown in your last screenshot appears. Such error seems to prevent us from changing other entities.

#1142 should fix this issue by initializing self._attr_native_value to None so that it ignore pattern check when self.state is called until self._attr_native_value is updated with the device value.

**Comment by dixon777** [comment]
I doubt it can be installed directly from HACS since it has not been merged. I would suggest either the changes through other means, such as [git command](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)(haven't tried but think it should work), or directly editing the related updated files if the former method doesn't work out.

**Comment by sulliwane** [comment]
Thanks for your answer.

Do you have an idea regarding when we can expect your pull request to be merged?

Also, do you see any value in my trying your patch to make sure it solves the above problem? 

Depending on that, I'll decide whether I locally try the fix, or wait for official version to be released :)

**Comment by dixon777** [comment]
@sulliwane 
> Do you have an idea regarding when we can expect your pull request to be merged?

According to my experience, when PR involved modification more than just adding or fixing device converters, it took quite a long time until the PR gets reviewed. It's been almost 2 months and yet there hasn't been any comment on #1142. I can't be sure when it will be merged and would recommend you to try to fix it yourself locally.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.0
