### ISSUE TITLE
unsupported modell: lumi.ctrl_neutral2.v3

### ISSUE THREAD

**Issue by ptbsare** [AlexxIT/XiaomiGateway3#163]
···
2021-01-04 21:53:36  DEBUG    gateway3      192.168.195.181 | lumi.158d0003d1ee15 has an unsupported modell: lumi.ctrl_neutral2.v3

···

**Comment by ptbsare** [comment]
https://github.com/AlexxIT/XiaomiGateway3/blob/40e36b441039a240602fcb553d7b6e060efa0a09/custom_components/xiaomi_gateway3/core/utils.py#L416

**Comment by ptbsare** [comment]
add '.v3' ?
```python
 if zigbee_model.endswith(('.v1', '.v2', 'v3')): 
```

**Comment by rezmus** [comment]
where did you get it? there is not such model in mijia/aqara ecosystem.

**Comment by ptbsare** [comment]
I bought it from a aqara store. Adding the '.v3' fixed the issue.

**Comment by rezmus** [comment]
must be something new. can you share photo of box (back side)? or at least model from the box.

**Comment by ptbsare** [comment]
![IMG_20210105_200607](https://user-images.githubusercontent.com/3147576/103644714-c7733300-4f91-11eb-9805-a236304d1d29.jpg)
It looks likes the same with V2, It is already installed, so I can not show the back side. :D

**Comment by rezmus** [comment]
i mean product box, but it does not matter ;) btw: can you buy t1 sensors in china already? heard they are hard to buy, only wholesale market and not online for retail.

**Comment by froggyfly** [comment]
> i mean product box, but it does not matter ;) btw: can you buy t1 sensors in china already? heard they are hard to buy, only wholesale market and not online for retail.

T1 series, not only sensors but also their new zigbee3.0 products are not sell online.  Aqara only offer these series to their offline stores. There're a little can be find on the second-hand market only.

Since Xiaomi began to develop Bluetooth mesh technology, no longer the zigbee, Aqara is more and more far away from Xiaomi, Aqara cooperate with apple and open more and more offline stores. New product launches on the Internet are almost stagnant.

**Comment by AlexxIT** [comment]
Supported in latest beta versions. Will appear in the next release.
