### ISSUE TITLE
XIAOMI Mijia Bluetooth Thermometer 2

### ISSUE THREAD

**Issue by vorlocsev** [AlexxIT/XiaomiGateway3#2]
Still undiscovered
![Screenshot_20200831-201619_Mi Home](https://user-images.githubusercontent.com/69817726/91747722-5aa4f200-ebc7-11ea-8ecb-d638a455d172.jpg)
![Screenshot_20200831-201909_Mi Home](https://user-images.githubusercontent.com/69817726/91747927-c1c2a680-ebc7-11ea-810b-1ace1a8bb679.jpg)

**Comment by scrambledleek** [comment]
It says in the description that bluetooth devices are not yet supported.  This is partly because their events don't go via the MQTT broker.

The bluetooth events are visible in /var/log/messages, so creating a little script which sucks the bluetooth event data from /var/log/messages and publishes it to the MQTT broker might be useful (if all of the useful data is present in /var/log/messages!).  The script could be created and launched via the telnet session when it relaunches mosquitto.

If @AlexxIT reckon's it's the way he'd like to go, maybe this script would be helpful:

```
#/bin/ash

# Script which monitors /var/log/messages on a Xiaomi Gateway 3 (ZNDMWG03LM)
# for asynchronous bluetooth events and publishes them to the mosquitto MQTT
# broker.

if [ -z "$LAST_TIMESTAMP" ] ; then
  # Get the curent time; don't publish anything earlier than it
  LAST_TIMESTAMP=`date +%s`
fi

# Field split only on newlines
IFS="
"

while true
do
  for line in `cat /var/log/messages | grep ble_event`; do
    TS=`echo $line | sed "s/.*gwts\":\([0-9]*\).*/\1/"`
    DID=`echo $line | sed "s/.*did\":\"\([^\"]*\)\".*/\1/"`
    PAYLOAD=`echo $line | sed "s/.*TX: \(.*\)/\1/`
    if [ $TS -ge $LAST_TIMESTAMP ] ; then
      mosquitto_pub -t ble/event/$DID -m \'$PAYLOAD\'
      LAST_TIMESTAMP=$TS
    fi
  done
  sleep 20s
done
```
I only have some bluetooth temperature and humidity sensors and haven't decoded what the event IDs and event data I'm seeing mean just yet...

**Comment by AlexxIT** [comment]
Added support in latest release

**Comment by bubez81** [comment]
hello, did you remove bluetooth to MQTT support?

**Comment by AlexxIT** [comment]
BLE in MQTT was only for retain after Hass restarts. This is no longer needed

**Comment by bubez81** [comment]
I understand, I used this function to also have the miflora data in the homebridge via mqtt
