### ISSUE TITLE
got un-responsible after certain period

### ISSUE THREAD

**Issue by latel** [AlexxIT/XiaomiGateway3#236]
This project is great, but always loose response after a certian time

![image](https://user-images.githubusercontent.com/5621862/109022138-80363280-76f6-11eb-895f-3c10ed5784fd.png)

**Comment by latel** [comment]
Last time I get into this probleam, I have to reset the gateway to solve the problem, however, it's unrealistic to do this everytime.

**Comment by AlexxIT** [comment]
Wrong token or gateway IP

**Comment by latel** [comment]
noop, it works alright after reset, after couple of days or weeks it stuck like this, I do nothing else, I didn't reset any device or gateway linked in

**Comment by AlexxIT** [comment]
This also can be if problems with Internet on Cloud. Because miio protocol can don't work without Internet.

**Comment by fredvaz** [comment]
The same issue here. I ran some test cases and when this happens with my Gateway 3 Software version 1.4.7_0115:
- Gateway devices are unavailable on Home Assistant but still running on Mi Home and controllable through Mi automation;
- Reset the Gateway or the Wi-Fi Router by turn off/on the power didn't fix the issue;
- Reset the Home Assistant fixed the issue;
- I didn't find any issues with the network setup with the other devices like Wifi Bulbs through Home Assistant keep going available and controllable. However, with 'yeelight_mono5' we have some occurrences 'Bulb closed the connection' and 'A socket error occurred when sending the command' at 04:42h and then Gateway 3 issue;
- I'm using the duckdns and set on the main router the port forwarding 443 and 80 TCP to 8123 gateway router where Gateway 3 and all my devices are connected. Then gateway router port forwarding 8123 to RPI/Home Assistant.

In the below figure, the issue first occurrence was at 4:53h after the Gateway reset at ~00:00h. Also, there is an additional error log at 5:25h. The issue appears in short periods of 5h. 
![Home-Assistant-Log_A](https://user-images.githubusercontent.com/11358115/110933360-8d713500-8324-11eb-8d0b-0bc4b52e3afc.PNG)

After resetting the Home Assistant this morning at 12:00h, similar errors, then Gateway devices unavailable. Router reset issue kept. Home Assistant reset fixed the issue.   
![image](https://user-images.githubusercontent.com/11358115/110938370-aaf5cd00-832b-11eb-9bcf-2c916f094f40.png)

Next step: I will remove 'yeelight_mono5' from Home Assistant in order to verify if the Gateway 3 issue stills or not.

Btw, Awesome project! Keep the hard work! 🥇

**Comment by xedsvg** [comment]
I have the same problems but when my router decides (randomly) to crap itself out. (Wifi is still on but not routing {hass, xiaomi bridge} -> unifi ap -> isp router).
My solution is to telnet into the xiaomi bridge and kill all the socat processes except the first one. (based on pid).

Maybe we can think a hearbeat process linked with hass and if no connection then restart almost everything?

**Comment by fredvaz** [comment]
> (ZHA Implementation)
> I have the same problems but when my router decides (randomly) to crap itself out.
> (Wifi is still on but not routing {hass, xiaomi bridge} -> unifi ap -> isp router).
> 
> My solution is to telnet into the xiaomi bridge and kill all the socat processes except the first one. (based on pid).
> 
> Maybe we can think a hearbeat process linked with hass and if no connection then restart almost everything?

Are you using the Xiaomi Gateway 3 Integration in ZHA mode? 
There is a recent issue reported about 'ZHA - Network dies once a day or becomes "flaky"'. Check here:
#47982: https://github.com/home-assistant/core/issues/47982

**Comment by kkmaslowski** [comment]
Anyone with stabillity problem - please post your firmware version and info it it's modded or original.

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
