### ISSUE TITLE
It's possible to change Mi Flora mac address?

### ISSUE THREAD

**Issue by logrodiego** [AlexxIT/XiaomiGateway3#395]
Hi all: I bought 4 Mi Flora from Huahuacaocao but I have a big problem, all of the has the same MAC Address (80:EA:CA:60:05:05)!

I found this problem turning on 1 by 1 the My Flora's sensors and using this command in Raspberry pi: sudo hcitool lescan.

I tried to use HHCC app and the same happened, I can only add 1 of them, but not the rest of the items :(.

The question is, any of you know how can I change MAC address of this my flora sensors?.

If nowone knows about how can I do it, any of you knows a support contact email from the manufacter?

Thank you so much for your support.

**Comment by AlexxIT** [comment]
Are you sure it's the Mi Flora that's displayed and not some other device?

**Comment by logrodiego** [comment]
> Are you sure it's the Mi Flora that's displayed and not some other device?

Thank you for answer. Im sure of it. If i Connected one to my flora in hhcc app and if i remove the battery of this myflora and put a battery un other one hhcc conects to the other one without create a new connection.
I checked with the luminosity of the item to be sure.
I checked It searching bluetooth equipments too.

**Comment by Shield79** [comment]
Hi, same issue here:-( Purchased 32 pieces and 11 has the same MAC - 80:EA:CA:60:05:05. I have purchased these over AliExpress so I have submitted a dispute requesting a fix or refund, lets see, anyway I would appreciate fix instead of waiting. This looks like global issue where someone was not pushing in the correct configuration

**Comment by AlexxIT** [comment]
Can you give link to Ali?

**Comment by insertjokehere** [comment]
I'm having the same issue! Thought I was going crazy for a bit, but yes, all 3 Mi Flora sensors are broadcasting the same MAC, and its the same as the one yours are - 80:EA:CA:60:05:05

**Comment by AlexxIT** [comment]
I think the problem cannot be solved and the issue can be closed

**Comment by arunvishnu** [comment]
@insertjokehere @Shield79 @logrodiego 
Did any one of you find a resolution for this? I have the same issue and the aliexpress seller is not agreeing to this issue and keep rejecting the dispute

**Comment by insertjokehere** [comment]
@arunvishnu Nope, sorry. I managed to get them refunded only because they arrived very late. Ordered another batch from a different seller and these ones worked as expected. I've got 1 of the ones with a bad MAC in operation, gave another to a friend, will probably take the 3rd to work once I figure out how to get something to report back into my HomeAssistant instance

**Comment by alexanderznamensky** [comment]
the same issue..... bought 3 pcs with same MACs - 80:EA:CA:60:05:05
