### ISSUE TITLE
2 gateways BLE issue

### ISSUE THREAD

**Issue by brainiac19** [AlexxIT/XiaomiGateway3#977]
I found #968 which describes the exact problem I'm facing. A BLE device is connected via gw1 initially but later it shows `connected via gw2` in device info page and cannot be controlled. In Mi Home the device still works but not in HA anymore. Gw1 is closer to said device and gw2 further away of course.

It is mentioned under #968 that BLE devices just radio signals, but in my case the BLE device doesn't actually belong to any BLE mesh network but can only talk to gw1, since it's too far from any other BLE device other than gw1, and therefore cannot be controlled when HA somehow believes it should talk to this BLE device through gw2, which is pretty far from it and only works sometimes.

**Comment by brainiac19** [comment]
In another word, I don't think gw1 and gw2 and all their BLE devices can form a large BLE mesh network in my case, they need LAN to communicate.

**Comment by ProjectA31** [comment]
I have the same issue with one of my BLE device. Integration version is v3.1.0. 

I have Gw1 ZNDMWG03LM with firmware 1.5.0_0102, Gw2 DMWG03LM with firmware 1.0.3_0028, and Gw3 ZNDMWG03LM with firmware 1.5.0 added to HA.

The BLE switch with problem is far from Gw3 and Gw2, but very close to Gw1. So also Gw1 is far away from Gw2 and Gw3.

The switch works normally with MI home or other integrations in HA. It also works normally if I only add Gw1 to HA by this integration. However after Gw2 and Gw3 are added for a while, I cannot/failed turn on or off the BLE switch through HA (the switch button in HA is enabled anyway,  but if you toggle it, it changes, then quickly goes back to the previous state, and the physical switch does not response to this operation). However, the switch on off state does update correctly in HA if I toggle the switch through MI home. 

In MI Home, the switch is only shown under Gw1, which is because the switch is too far away from the other two gateways. However in HA, it is shown under all the 3 gateways, I guess this causes the problem, if the integration tries to control the switch by Gw2 or Gw3, not Gw1. Any ideas?

Thanks.

**Comment by AlexxIT** [comment]
Please provide your gateways firmwares and models. And your BLE models you talking about.

**Comment by brainiac19** [comment]
Two gateways: gateway ZNDMWG03LM Firmware: 1.5.0_0102
The mesh switch that sometimes offline: mesh DHKG01ZM

**Comment by AlexxIT** [comment]
Update to 1.5.4. It has a lot of fixes for BLE/Mesh

**Comment by brainiac19** [comment]
Right and I just noticed the v3.2.0 update on this repo. Thank you for your work and I'll report if any problem surfaces.

**Comment by ProjectA31** [comment]
Just upgraded the integration to v3.2.1, and all the three gateways to the latest firmware version. The issue still exists for one of my BLE mesh switches. The switch model is not recognized, shows as "mesh (4380)".

However, I figured out that renaming or reloading the integration of gateway Gw2 (DMWG03LM) can solve this issue. After reloading the integration of the gateway Gw2, the entity of the BLE switch will be changed to in Gw1 instead of Gw2. I think that fixes the problem. So I create an automation to auto reload integration of Gw2 when HA is started. So far, it works well.

**Comment by lxz946786639** [comment]
Will this issue be fixed in the future? When multiple multi-mode accesses, distant devices will occasionally become unavailable.

**Comment by vitaxiao** [comment]
I met the same problem. I have two gateways DMWG03LM with 1.0.6_0016 and ZNDMWG03LM with 1.5.4_0090, each on different floor. I am running 3.2.1 plugin on HA 2023.5.4, and I believe the issue was there before upgrade plugin and HA versions.

I have Mesh Wall Switches on both floors, all the mesh devices show up in both gateways, however, entities will only appear on one side. Once I disable the BLE support in one gateway options, all the entities will move into the other gateway, however become unavailable if they are on different floor. Even I re-enable BLE support on previous gateway, those entity still cannot be controlled.  
Tried to hack "via_device_id" in core.device_registry, but no luck, as it will always change again.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v3.3.0
